// Code generated by protoc-gen-go.
// source: pinba.proto
// DO NOT EDIT!

/*
Package Pinba is a generated protocol buffer package.

It is generated from these files:
	pinba.proto

It has these top-level messages:
	Request
*/
package Pinba

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Request struct {
	Hostname         *string    `protobuf:"bytes,1,req,name=hostname" json:"hostname,omitempty"`
	ServerName       *string    `protobuf:"bytes,2,req,name=server_name" json:"server_name,omitempty"`
	ScriptName       *string    `protobuf:"bytes,3,req,name=script_name" json:"script_name,omitempty"`
	RequestCount     *uint32    `protobuf:"varint,4,req,name=request_count" json:"request_count,omitempty"`
	DocumentSize     *uint32    `protobuf:"varint,5,req,name=document_size" json:"document_size,omitempty"`
	MemoryPeak       *uint32    `protobuf:"varint,6,req,name=memory_peak" json:"memory_peak,omitempty"`
	RequestTime      *float32   `protobuf:"fixed32,7,req,name=request_time" json:"request_time,omitempty"`
	RuUtime          *float32   `protobuf:"fixed32,8,req,name=ru_utime" json:"ru_utime,omitempty"`
	RuStime          *float32   `protobuf:"fixed32,9,req,name=ru_stime" json:"ru_stime,omitempty"`
	TimerHitCount    []uint32   `protobuf:"varint,10,rep,name=timer_hit_count" json:"timer_hit_count,omitempty"`
	TimerValue       []float32  `protobuf:"fixed32,11,rep,name=timer_value" json:"timer_value,omitempty"`
	TimerTagCount    []uint32   `protobuf:"varint,12,rep,name=timer_tag_count" json:"timer_tag_count,omitempty"`
	TimerTagName     []uint32   `protobuf:"varint,13,rep,name=timer_tag_name" json:"timer_tag_name,omitempty"`
	TimerTagValue    []uint32   `protobuf:"varint,14,rep,name=timer_tag_value" json:"timer_tag_value,omitempty"`
	Dictionary       []string   `protobuf:"bytes,15,rep,name=dictionary" json:"dictionary,omitempty"`
	Status           *uint32    `protobuf:"varint,16,opt,name=status" json:"status,omitempty"`
	MemoryFootprint  *uint32    `protobuf:"varint,17,opt,name=memory_footprint" json:"memory_footprint,omitempty"`
	Requests         []*Request `protobuf:"bytes,18,rep,name=requests" json:"requests,omitempty"`
	Schema           *string    `protobuf:"bytes,19,opt,name=schema" json:"schema,omitempty"`
	TagName          []uint32   `protobuf:"varint,20,rep,name=tag_name" json:"tag_name,omitempty"`
	TagValue         []uint32   `protobuf:"varint,21,rep,name=tag_value" json:"tag_value,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func (m *Request) GetServerName() string {
	if m != nil && m.ServerName != nil {
		return *m.ServerName
	}
	return ""
}

func (m *Request) GetScriptName() string {
	if m != nil && m.ScriptName != nil {
		return *m.ScriptName
	}
	return ""
}

func (m *Request) GetRequestCount() uint32 {
	if m != nil && m.RequestCount != nil {
		return *m.RequestCount
	}
	return 0
}

func (m *Request) GetDocumentSize() uint32 {
	if m != nil && m.DocumentSize != nil {
		return *m.DocumentSize
	}
	return 0
}

func (m *Request) GetMemoryPeak() uint32 {
	if m != nil && m.MemoryPeak != nil {
		return *m.MemoryPeak
	}
	return 0
}

func (m *Request) GetRequestTime() float32 {
	if m != nil && m.RequestTime != nil {
		return *m.RequestTime
	}
	return 0
}

func (m *Request) GetRuUtime() float32 {
	if m != nil && m.RuUtime != nil {
		return *m.RuUtime
	}
	return 0
}

func (m *Request) GetRuStime() float32 {
	if m != nil && m.RuStime != nil {
		return *m.RuStime
	}
	return 0
}

func (m *Request) GetTimerHitCount() []uint32 {
	if m != nil {
		return m.TimerHitCount
	}
	return nil
}

func (m *Request) GetTimerValue() []float32 {
	if m != nil {
		return m.TimerValue
	}
	return nil
}

func (m *Request) GetTimerTagCount() []uint32 {
	if m != nil {
		return m.TimerTagCount
	}
	return nil
}

func (m *Request) GetTimerTagName() []uint32 {
	if m != nil {
		return m.TimerTagName
	}
	return nil
}

func (m *Request) GetTimerTagValue() []uint32 {
	if m != nil {
		return m.TimerTagValue
	}
	return nil
}

func (m *Request) GetDictionary() []string {
	if m != nil {
		return m.Dictionary
	}
	return nil
}

func (m *Request) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *Request) GetMemoryFootprint() uint32 {
	if m != nil && m.MemoryFootprint != nil {
		return *m.MemoryFootprint
	}
	return 0
}

func (m *Request) GetRequests() []*Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *Request) GetSchema() string {
	if m != nil && m.Schema != nil {
		return *m.Schema
	}
	return ""
}

func (m *Request) GetTagName() []uint32 {
	if m != nil {
		return m.TagName
	}
	return nil
}

func (m *Request) GetTagValue() []uint32 {
	if m != nil {
		return m.TagValue
	}
	return nil
}

func init() {
}
